### ISSUE TITLE
spurious Capybara::OptionNotFound

### ISSUE THREAD

**Issue by rjharmon** [smparkes/capybara-envjs#10]
Capybara::OptionNotFound: No such option 'Sales' in this select box. Available options: 'All Categories', 'Returns', 'Sales'

Seems like all_unfiltered("//option[text()='#{option}']") isn't matching what we'd figure on it matching...

**Comment by smparkes** [comment]
Hmmm ... does this work against the normal rack-test driver (just to narrow things down).

Any chance you have/could create a small, self-contained test case?

**Comment by smparkes** [comment]
I'm gong to push an update soon that tweaks this, following some escaping from the new capy changes. I don't know that it's going to affect this, though, since that example doesn't require any escaping.

If it's still a problem I'm going to need some kind of test case. There are lots of tests for this that pass, so I'm not sure what corner case you're hitting ...

**Comment by rjharmon** [comment]
Sorry for lagging, we're stealing time when we can to add behavioral tests.  I'll see what I can do to trim our case to the minimum but it might take another week :(

**Comment by smparkes** [comment]
I know how that goes.

I saw this

http://tinyurl.com/3yk8use

which might mean this is a generic capy issue, not something specific to the envjs driver.

**Comment by sbleon** [comment]
This looks like it has been fixed as of Capybara 0.4 (according to post at http://tinyurl.com/3yk8use). I think this issue can be closed.

**Comment by smparkes** [comment]
Thanks. I'll close. Please reopen/open new if there's still an issue.
